"""PartsAPI shop method signatures from the owner export of 2026-09-25."""

PARTSAPI_SHOP_METHODS: dict[str, tuple[str, ...]] = {
    "getMakes": ("carType",),
    "getModels": ("carType", "makeId", "lang"),
    "getCars": ("makeId", "carType", "modelId"),
    "getSearchTree": ("lang", "carId", "carType"),
    "getArticles": ("lang", "strId", "carId", "carType"),
    "getArticle": ("LANG", "ART_NUM", "SUP_ID"),
    "getArticleMedia": ("ART_ID", "LANG"),
    "getArticleCrosses": ("ART_ID", "LANG"),
    "getArticleCriteria": ("ART_ID", "LANG"),
    "getApplicability": ("sku", "brand"),
    "getApplicability2": ("sku",),
    "getFullInfoCV": ("LANG", "COUNTRY", "CV_ID"),
    "searchArticles": ("SEARCH_NUMBER", "LANG"),
    "tecdocCrosses": ("number",),
    "getEngine": ("TYPE", "TYPE_ID", "LANG"),
    "getPassengerCarInfo": ("carId", "lang"),
    "getProductGroupsByBrandNumber": ("brand", "sku", "lang"),
    "VINdecode": ("vin", "lang"),
    "decodeVINus": ("vin",),
    "gosnomer2vin": ("gosnomer",),
    "GetNormsMakes": (),
    "GetNormsModels": ("makeNameSEO",),
    "GetNormsMotors": ("modelId",),
    "GetNormsTimes": ("motorId", "TopCatId", "SubCatId"),
    "GetFillVolumes": ("carId",),
    "toMakes": (),
    "toModels": ("brandId",),
    "toTypes": ("modelId",),
    "toParts": ("typeId",),
    "toDopusk": ("typeId",),
    "toOils": ("typeId",),
    "FindEAN13": ("brand", "number"),
    "PartSuggest": ("oem",),
    "getCrosses": ("number",),
    "getCrossesTitle": ("lang", "number"),
    "getPartnameByBrandNumber": ("brand", "number", "lang"),
    "DecodeEAN13": ("code",),
    "getCrossesWithBrand": ("number", "brand"),
    "rusNameSuggest": ("firstName", "midName", "surName"),
    "getPartWeight": ("brand", "number"),
    "carImpoundment": ("number", "type"),
    "partNameSuggest": ("query",),
    "getCarsByOilSpecification": ("query",),
}
